### ISSUE TITLE
Nested dict argument to jinja macro fails the formatter

### ISSUE THREAD

**Issue by rparvathaneni-sc** [tconbeer/sqlfmt#471] opened 2023-08-31 18:28 UTC
**Describe the bug**
The following config macro makes the formatter fail because of the nested dict (range in partition_by)
```
{{ config(
    materialized='table',
    partition_by={
      "field": "user_id",
      "data_type": "int64",
      "range": {
        "start": 0,
        "end": 100,
        "interval": 10
      }
    }
)}}
```

**To Reproduce**
Paste the macro above in an sql file and try to run the formatter

**Expected behavior**
Formatter not erroring out

**Actual behavior**
```
sqlfmt encountered an error: Closing bracket ')' found at 138 before bracket was opened.
```

**Additional context**
What is the output of `sqlfmt --version`?
```
sqlfmt, version 0.19.0
```

**Comment by tconbeer** [comment] 2023-08-31 22:19
I can't repro on `main` or sqlfmt.com.

**Comment by benjamin-awd** [comment] 2023-10-12 10:20
I've run into a similar issue -- plugging the code into sqlfmt.com works fine though, so I'm just manually replacing the buggy code

Original code:
```
{{
    config(
        materialized='incremental',
        incremental_strategy='insert_overwrite',
        external_location=generate_external_location("bucket", "datalake/xxx"),
        partitioned_by=['batch_date'],
        lf_tags_config={
          'enabled': true,
          'tags': {
            'domain': 'foo',
            'sensitivity': 'bar'
          }
        }
    )
}}
```

After formatting:
```
{{
    config(
        materialized="incremental",
        incremental_strategy="insert_overwrite",
        external_location=generate_external_location("bucket", "datalake/xxx"),
        partitioned_by=["batch_date"],
        lf_tags_config={
            "enabled": true,
            "tags": {"domain": "foo", "sensitivity": "bar"},
        },
    )
}}
```

**Comment by tconbeer** [comment] 2023-10-12 16:29
Can you run pip list, please? I need to know what versions of shandy-sqlfmt and black you have installed.

**Comment by benjamin-awd** [comment] 2023-10-13 07:56
I have a pretty long list of dependencies, but in my project I'm using
```
black                               22.12.0
shandy-sqlfmt                       0.20.0
```

Some additional debugging messages, in case it's useful:
```
INFO:root:Token(type=TokenType.UNTERM_KEYWORD, token=select, spos=374)
INFO:root:Token(type=TokenType.UNTERM_KEYWORD, token=from, spos=1308)
INFO:root:Token(type=TokenType.UNTERM_KEYWORD, token=where, spos=1374)
INFO:root:Token(type=TokenType.BRACKET_CLOSE, token=), spos=310)
1 file had errors while formatting.
0 files left unchanged.
kp_dbt/dbt/app/models/kp_curated/web3/rpt_web3__subscription.sql
    sqlfmt encountered an error: Closing bracket ')' found at 310 before bracket was opened.
```

```
-> rule.action(self, source_string, match)
(Pdb) rule
Rule(name='bracket_close', priority=510, pattern='(\\]|\\)|\\})', action=functools.partial(<function add_node_to_buffer at 0x106a6cee0>, token_type=<TokenType.BRACKET_CLOSE: 19>))
(Pdb) match
<re.Match object; span=(310, 315), match='    )'>
```

**Comment by tconbeer** [comment] 2023-10-13 12:35
Thanks. Those logs are surprising -- the error is coming from pos 310, after later parts of the query are lexed... can you share the rest of your query (or another reproducible example), through the end of the where clause?

**Comment by benjamin-awd** [comment] 2023-10-14 09:47
This query triggers `sqlfmt encountered an error: Closing bracket ')' found at 330 before bracket was opened.`

```sql
{{
    config(
        materialized='incremental',
        incremental_strategy='insert_overwrite',
        external_location=generate_external_location("baz", "datalake/producer=foo/object=bar"),
        partitioned_by=['batch_date'],
        lf_tags_config={
          'enabled': true,
          'tags': {
            'domain': 'foo',
            'sensitivity': 'public'
          }
        }
    )
}}

select
    batch_date
from
    {{ ref('bar') }}
{% if is_incremental() %}
where batch_date = '{{ var("ds") }}'
{% endif %}
```

The issue seems linked to the line-length argument. Running `sqlfmt <path_to_query> --line-length 88` works fine, but `sqlfmt <path_to_query> --line-length 120` triggers the error.

I've pinpointed the missing comma as the issue -- if you add the comma, no errors are raised.
```diff
        lf_tags_config={
          'enabled': true,
          'tags': {
            'domain': 'foo',
            'sensitivity': 'public'
+          },
        }
```

**Comment by tconbeer** [comment] 2023-10-15 20:33
I can reproduce on `main`, only with a line length of 95 or greater, which is very strange.

**Comment by benjamin-awd** [comment] 2023-10-17 17:40
Looks like it's an issue with the `search_for_terminating_token` function

```
Starting var:.. start_rule = 'jinja_expression_start'
Starting var:.. program = re.compile('[^\\S\\n]*((\\{\\{-?)|(-?\\}\\}))', re.IGNORECASE|re.DOTALL)
Starting var:.. nesting_program = re.compile('[^\\S\\n]*(\\{\\{-?)', re.IGNORECASE|re.DOTALL)
Starting var:.. tail = ' config(lf_tags_config={"enabled": true, "tags": {"domain": "foo", "sensitivity": "public"}}) }}\n'
Starting var:.. pos = 2
00:52:32.838857 call       166     def search_for_terminating_token(
00:52:32.840292 line       179         match = program.search(tail)
New var:....... match = <re.Match object; span=(90, 92), match='}}'>
00:52:32.841333 line       180         if not match:
00:52:32.842425 line       186         start, end = match.span(1)
New var:....... start = 90
New var:....... end = 92
00:52:32.843606 line       188         nesting_match = nesting_program.match(tail, start)
New var:....... nesting_match = None
00:52:32.844716 line       189         if nesting_match:
00:52:32.846138 line       206             return pos + end
00:52:32.847240 return     206             return pos + end
Return value:.. 94
```

The correct start should be 94, and the correct end should be 96

> I can reproduce on main, only with a line length of 95 or greater, which is very strange.

On lengths < 95, the source_string doesn't have `}}` in it, which prevents this issue from occurring
```text
\n    config(\n        lf_tags_config={\n            "enabled": true,\n            "tags": {"domain": "foo", "sensitivity": "public"},\n        }\n    )\n}}\n
```

It might be possible to solve this with some kind of parsing logic that checks the tail to see if it contains a dictionary. Otherwise, maybe some kind of initial pass to add trailing commas to } delimiters? That would prevent the end of the dictionary from being read as a jinja comment, since it becomes `...public"},}` instead of `...public"}}`

**Comment by tconbeer** [comment] 2023-10-20 18:41
Thanks so much! I've been traveling - it's on my list to review this and get the other one merged today; might slip to early next week. Really appreciate your engagement here!

**Closed** 2023-10-20 21:45 UTC
Labels: bug
